#!/usr/bin/env python3
"""
Overlays a fixed, original mascot illustration in the bottom-right corner of
the generated episode video, when the episode's series has one.

Free and self-contained: mascots are hand-drawn SVG/PNG assets generated by
assets/characters/generate_mascots.py and committed in assets/characters/,
not fetched from any third party or generated by an image API. This is a
cheap way to give a series a recognizable "cast" without needing a full
animated/rigged character, which this project's zero-cost stock-footage
pipeline cannot produce. When a series has more than one character, one is
picked at random per episode from that series' own cast only (see
SERIES_MASCOTS below) -- so which character appears can vary episode to
episode, but never crosses over into a different series' characters.

Usage: python scripts/overlay_mascot.py result.json "<video subject>"
No-ops (exit 0) if the subject's series has no mascot asset, or if ffmpeg
is unavailable -- this step must never fail the workflow.
"""
import glob
import os
import random
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
CHARACTERS_DIR = os.path.join(ROOT, "assets", "characters")

# Maps each series name (the part of the video subject before " - Capitulo")
# to its cast of mascot image files. When a series has more than one
# character, one is picked at random per episode -- but always from that
# series' own cast, never mixed with another series' characters, so the
# episode-to-episode variation stays coherent with what's on screen.
SERIES_MASCOTS = {
    "Luna, la zorrita curiosa": ["luna_fox.png"],
    "Tobías y el barco de papel": ["tobias_boy.png"],
    "El elefante invisible": ["pipo_elephant.png"],
    "La isla de luna llena": ["mar_sister.png", "leo_brother.png"],
    "El rey que aprendió a escuchar": ["teodoro_king.png", "alba_villager.png"],
}


def _series_name(subject: str) -> str:
    return subject.split(" - Capitulo", 1)[0].strip()


def _find_output_video() -> str | None:
    candidates = glob.glob(
        os.path.join(ROOT, "storage", "tasks", "**", "*.mp4"), recursive=True
    )
    if not candidates:
        return None
    # The final combined render is the most recently written mp4.
    return max(candidates, key=os.path.getmtime)


def main() -> int:
    if len(sys.argv) < 3:
        print("usage: overlay_mascot.py result.json <video subject>", file=sys.stderr)
        return 0  # never fail the workflow over a usage error here

    subject = sys.argv[2]
    series = _series_name(subject)
    cast = SERIES_MASCOTS.get(series)
    if not cast:
        print(f"no mascot configured for series '{series}', skipping overlay")
        return 0

    mascot_file = random.choice(cast)
    mascot_path = os.path.join(CHARACTERS_DIR, mascot_file)
    if not os.path.exists(mascot_path):
        print(f"mascot asset missing: {mascot_path}, skipping overlay")
        return 0

    if not shutil.which("ffmpeg"):
        print("ffmpeg not found, skipping mascot overlay")
        return 0

    video_path = _find_output_video()
    if not video_path:
        print("no rendered mp4 found, skipping mascot overlay")
        return 0

    tmp_output = video_path + ".with_mascot.mp4"
    # Mascot at ~22% of the video's width, anchored bottom-right with a small
    # margin, present for the whole clip -- a fixed "host" watching over the
    # story rather than a fully lip-synced character.
    filter_complex = (
        "[1:v]scale=iw*0.22:-1[mascot];"
        "[0:v][mascot]overlay=W-w-24:H-h-24:format=auto"
    )
    cmd = [
        "ffmpeg", "-y",
        "-i", video_path,
        "-i", mascot_path,
        "-filter_complex", filter_complex,
        "-c:a", "copy",
        tmp_output,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ffmpeg overlay failed, keeping original video:\n{result.stderr[-2000:]}")
        if os.path.exists(tmp_output):
            os.remove(tmp_output)
        return 0

    os.replace(tmp_output, video_path)
    print(f"mascot overlay applied: {mascot_file} -> {video_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
